# Generated by Django 5.1.4 on 2024-12-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('author', models.CharField(max_length=250, verbose_name='автор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('materials', models.TextField(verbose_name='Материлы')),
                ('photo', models.ImageField(upload_to='images/')),
                ('date_time', models.DateTimeField(verbose_name='Дата мероприятия')),
                ('places', models.IntegerField(verbose_name='Всего мест')),
            ],
        ),
    ]
