# Generated by Django 5.1.4 on 2024-12-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='available_seats',
            field=models.PositiveIntegerField(default=0, verbose_name='*'),
        ),
        migrations.AddField(
            model_name='events',
            name='total_seats',
            field=models.PositiveIntegerField(default=0, verbose_name='свободные места'),
        ),
    ]
