# Generated by Django 5.1.4 on 2025-01-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_eventparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='author',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='events',
            name='materials',
            field=models.TextField(blank=True, null=True, verbose_name='Материлы'),
        ),
        migrations.AlterField(
            model_name='events',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
