# Generated by Django 5.1.4 on 2025-01-07 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_events_author_alter_events_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('author', models.CharField(blank=True, max_length=250, null=True, verbose_name='Автор')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('materials', models.TextField(blank=True, null=True, verbose_name='Материалы')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='event',
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='number_of_people',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество человек'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время сеанса')),
                ('total_seats', models.PositiveIntegerField(default=0, verbose_name='Всего мест')),
                ('available_seats', models.PositiveIntegerField(default=0, verbose_name='Свободные места')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='main.event', verbose_name='Мероприятие')),
            ],
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.eventsession', verbose_name='Сеанс мероприятия'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
