# Generated by Django 5.1.4 on 2025-01-07 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_event_remove_eventparticipant_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.eventsession', verbose_name='Сеанс мероприятия'),
        ),
    ]
