# Generated by Django 5.1.4 on 2025-01-07 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_eventparticipant_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='session',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.eventsession', verbose_name='Сеанс мероприятия'),
        ),
    ]
